name: generate space invaders animation

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch: # permite rodar manualmente
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - name: generate space invaders animation
        uses: UltimateStrength/space-invaders-contributions@v1
        with:
          github_user_name: UltimateStrength
          outputs: |
            dist/invaders.svg
            dist/invaders-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
